# Generated by Django 2.2 on 2019-09-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190924_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_document',
            old_name='output',
            new_name='docfile',
        ),
    ]
