# Generated by Django 2.2 on 2019-09-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190924_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(blank=True, upload_to='documents/Raw Data/'),
        ),
        migrations.AlterField(
            model_name='new_document',
            name='docfile',
            field=models.FileField(blank=True, upload_to='documents/Final Output/'),
        ),
    ]
