# Generated by Django 2.2 on 2019-09-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190924_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d/Raw Data/'),
        ),
        migrations.AlterField(
            model_name='new_document',
            name='docfile',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d/Final Output/'),
        ),
    ]
