# Generated by Django 2.2 on 2019-09-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190925_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(blank=True, upload_to='documents/%Y/%B/%a/Raw Data/'),
        ),
        migrations.AlterField(
            model_name='new_document',
            name='docfile',
            field=models.FileField(blank=True, upload_to='documents/%Y/%B/%a/Final Output/'),
        ),
    ]
